import "./globals.css";
import PageLayout from "@/components/Layout/PageLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className="dark">
      <body
        style={{direction: "rtl"}}
        className="transition-colors duration-300 font-kalameh"
      >
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
